/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CONFIGURACIONES.java
 *
 * Created on 26/05/2010, 03:39:41 PM
 */

package configuraciones;

import com.mysql.jdbc.ResultSetMetaData;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import javax.swing.table.TableModel;
import modelo.conexion_base_de_datos;

/**
 *
 * @author AN
 */
public class CONFIGURACIONES extends javax.swing.JFrame {

    /** Creates new form CONFIGURACIONES */
    public CONFIGURACIONES() {
        initComponents();
    }

    public JTable getInformacion() {
        return informacion;
    }

    public void setInformacion(JTable informacion) {
        this.informacion = informacion;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    conexion_base_de_datos cbd = new conexion_base_de_datos();
    ResultSet resultado=null;
    Statement sentencia=null;
    ResultSetMetaData metadatos;


    TableColumn columnas = new TableColumn();

    DefaultTableModel d= new DefaultTableModel();

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        informacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        informacion.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(informacion);

        jTabbedPane1.addTab("tab1", jScrollPane1);

        jTextField1.setText("jTextField1");

        jLabel1.setText("CEDULA");

        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnas(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buscar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buscar))
                .addGap(27, 27, 27)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void columnas(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnas
        try {
            sentencia = cbd.getConexion().createStatement();
            resultado = sentencia.executeQuery("SELECT * FROM control_de_estudio.notas_cet_2007");
            metadatos = (ResultSetMetaData) resultado.getMetaData();
            //resultado.next();
           
            
            this.getInformacion().setModel(d);

           // System.out.println("RESPUESTA");
           // System.out.println(metadatos.getColumnCount()+" - "+metadatos.getColumnName(2)+" "+resultado.getString("CEDULA"));


            for(int i=1; i<=metadatos.getColumnCount();i++){
                d.addColumn(metadatos.getColumnName(i));
            }

            


            sentencia.close();
            resultado.close();
            
            cbd.getConexion().close();


           // this.getInformacion().addColumn(columnas);
            // d.addColumn("andy");
        } catch (SQLException ex) {
            Logger.getLogger(CONFIGURACIONES.class.getName()).log(Level.SEVERE, null, ex);
        }
      
        
    }//GEN-LAST:event_columnas

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CONFIGURACIONES().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTable informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
