/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * convalidacion.java
 *
 * Created on 16/11/2010, 01:54:48 PM
 */

package vista;

import controlador.control_convalidaciones;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author AN
 */
public class convalidacion extends javax.swing.JFrame {

    /** Creates new form convalidacion */
    public convalidacion() {
        initComponents();
        this.academico.setText("1-2011");

        control_convalidaciones cc = new control_convalidaciones(this);
        buscar.addActionListener(cc);
        simular.addActionListener(cc);
        convalidar.addActionListener(cc);
        


    }

    public JLabel getAcademico() {
        return academico;
    }

    public void setAcademico(JLabel academico) {
        this.academico = academico;
    }

    public JComboBox getCambios() {
        return cambios;
    }

    public void setCambios(JComboBox cambios) {
        this.cambios = cambios;
    }

    public JTextField getCarrera() {
        return carrera;
    }

    public void setCarrera(JTextField carrera) {
        this.carrera = carrera;
    }

    public JTextField getCedula() {
        return cedula;
    }

    public void setCedula(JTextField cedula) {
        this.cedula = cedula;
    }

    public JTextField getCod_opsu() {
        return cod_opsu;
    }

    public void setCod_opsu(JTextField cod_opsu) {
        this.cod_opsu = cod_opsu;
    }

    public JTextField getEstudiante() {
        return estudiante;
    }

    public void setEstudiante(JTextField estudiante) {
        this.estudiante = estudiante;
    }

    public JTable getInformacion() {
        return informacion;
    }

    public void setInformacion(JTable informacion) {
        this.informacion = informacion;
    }

    public JTextField getVigencia() {
        return vigencia;
    }

    public void setVigencia(JTextField vigencia) {
        this.vigencia = vigencia;
    }

    public JTextField getMat_equi() {
        return mat_equi;
    }

    public void setMat_equi(JTextField mat_equi) {
        this.mat_equi = mat_equi;
    }

    public JTextField getUc_equi() {
        return uc_equi;
    }

    public void setUc_equi(JTextField uc_equi) {
        this.uc_equi = uc_equi;
    }

   

    





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedula = new javax.swing.JTextField();
        buscar = new javax.swing.JButton();
        cambios = new javax.swing.JComboBox();
        simular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        informacion = new javax.swing.JTable();
        convalidar = new javax.swing.JButton();
        ex = new javax.swing.JLabel();
        cax = new javax.swing.JLabel();
        vix = new javax.swing.JLabel();
        cox = new javax.swing.JLabel();
        academico = new javax.swing.JLabel();
        estudiante = new javax.swing.JTextField();
        carrera = new javax.swing.JTextField();
        vigencia = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cod_opsu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uc_equi = new javax.swing.JTextField();
        mat_equi = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CONVALIDACIONES.......Desarrollado por el Ing. Cusatti Andy");

        cedula.setToolTipText("Ingrese la cedula del estudiante");

        buscar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        buscar.setText("BUSCAR");
        buscar.setToolTipText("Presionar para buscar al estudiante");

        cambios.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cambios.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "2007_2010", "2007_2009", "2009_2010" }));
        cambios.setToolTipText("Opcion del pensum actual al que se desea enviar al estudiante");

        simular.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        simular.setText("SIMULAR");
        simular.setToolTipText("Simula la equivalencia del estudiante presentado el resultado en la tabla");

        informacion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        informacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "SEMESTRE", "CODIGO", "ASIGNATURA", "UC"
            }
        ));
        informacion.setIntercellSpacing(new java.awt.Dimension(2, 2));
        jScrollPane1.setViewportView(informacion);

        convalidar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        convalidar.setText("CONVALIDAR");

        ex.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ex.setText("ESTUDIANTE:");

        cax.setFont(new java.awt.Font("Tahoma", 0, 14));
        cax.setText("CARRERA:");

        vix.setFont(new java.awt.Font("Tahoma", 0, 14));
        vix.setText("VIGENCIA:");

        cox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cox.setText("OPSU:");

        academico.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        academico.setText("1-2011");
        academico.setToolTipText("Vigencia Actual con el que sera registrada la convalidacion del estudiante");

        estudiante.setToolTipText("Nombres y Apellidos del estudiante");
        estudiante.setEnabled(false);

        carrera.setToolTipText("Carrera actual del estudiante");
        carrera.setEnabled(false);

        vigencia.setToolTipText("Vigencia o Pensum a la que se encuentra el estudiante");
        vigencia.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("CEDULA:");

        cod_opsu.setToolTipText("Codigo opsu del estudiante");
        cod_opsu.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("CAMBIO:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("TOTALES:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("UC:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("MATERIAS:");

        uc_equi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        uc_equi.setToolTipText("Unidades de Creditos aprobadas por equivalencia");
        uc_equi.setEnabled(false);

        mat_equi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mat_equi.setToolTipText("Cantidad de materias aprobadas por equivalencias");
        mat_equi.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 882, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ex, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(cax, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(vix)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                                    .addComponent(buscar)
                                    .addGap(54, 54, 54))
                                .addComponent(estudiante, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)
                                .addComponent(carrera, javax.swing.GroupLayout.DEFAULT_SIZE, 336, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cox)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cambios, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                        .addComponent(simular, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cod_opsu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(7, 7, 7))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(academico, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mat_equi, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(uc_equi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(570, 570, 570)
                        .addComponent(convalidar, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simular, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(cambios, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ex)
                    .addComponent(cox)
                    .addComponent(cod_opsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cax))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(vigencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(vix)))
                    .addComponent(academico))
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(convalidar, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uc_equi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(mat_equi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convalidacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel academico;
    private javax.swing.JButton buscar;
    private javax.swing.JComboBox cambios;
    private javax.swing.JTextField carrera;
    private javax.swing.JLabel cax;
    private javax.swing.JTextField cedula;
    private javax.swing.JTextField cod_opsu;
    private javax.swing.JButton convalidar;
    private javax.swing.JLabel cox;
    private javax.swing.JTextField estudiante;
    private javax.swing.JLabel ex;
    private javax.swing.JTable informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField mat_equi;
    private javax.swing.JButton simular;
    private javax.swing.JTextField uc_equi;
    private javax.swing.JTextField vigencia;
    private javax.swing.JLabel vix;
    // End of variables declaration//GEN-END:variables

}
