/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ficha.java
 *
 * Created on 08/02/2012, 06:18:14 PM
 */

package vista;

import controlador.control_ficha;
import javax.swing.JEditorPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.event.HyperlinkEvent;

/**
 *
 * @author AN
 */
public class ficha extends javax.swing.JFrame {

    /** Creates new form ficha */
    public ficha() {
        initComponents();
        escritorio.setContentType("text/html");
                


        control_ficha cf = new control_ficha(this);
        mostrar.addActionListener(cf);
        escritorio.addHyperlinkListener(cf);
        dibuja.addActionListener(cf);


        jScrollPane1.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        jScrollPane1.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);

    }

    public JEditorPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JEditorPane escritorio) {
        this.escritorio = escritorio;
    }

    public JPanel getCuadro() {
        return cuadro;
    }

    public void setCuadro(JPanel cuadro) {
        this.cuadro = cuadro;
    }






    



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        escritorio = new javax.swing.JEditorPane();
        mostrar = new javax.swing.JButton();
        cuadro = new javax.swing.JPanel();
        dibuja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(escritorio);

        mostrar.setText("MOSTRAR");

        cuadro.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        dibuja.setText("DIBUJA");
        dibuja.setActionCommand("DIBUJA");

        javax.swing.GroupLayout cuadroLayout = new javax.swing.GroupLayout(cuadro);
        cuadro.setLayout(cuadroLayout);
        cuadroLayout.setHorizontalGroup(
            cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroLayout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(dibuja)
                .addContainerGap(153, Short.MAX_VALUE))
        );
        cuadroLayout.setVerticalGroup(
            cuadroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuadroLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(dibuja)
                .addContainerGap(141, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 714, Short.MAX_VALUE)
                .addComponent(mostrar)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(cuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(341, 341, 341))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mostrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(cuadro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(150, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ficha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cuadro;
    private javax.swing.JButton dibuja;
    private javax.swing.JEditorPane escritorio;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mostrar;
    // End of variables declaration//GEN-END:variables

}
