/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * fondos.java
 *
 * Created on 20-may-2009, 10:52:53
 */

package vista;

import java.awt.Dimension;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author AACM
 */
public class fondos extends javax.swing.JPanel {

    /** Creates new form fondos */
    public fondos() {
        initComponents();
    }


public void paintComponent(Graphics g) {
Dimension tamanio = getSize();
ImageIcon fondo = new ImageIcon(getClass().getResource("/actualizacion_de_datos/imagenes/peligro-globos-aerostaticos-3.jpg"));
g.drawImage(fondo.getImage(), 0, 0, tamanio.width, tamanio.height, null);
setOpaque(false);
super.paintComponent(g);
}



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        jButton1.setText("andy");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(346, 346, 346)
                .add(jButton1)
                .addContainerGap(397, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(506, Short.MAX_VALUE)
                .add(jButton1)
                .add(71, 71, 71))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables

}
