/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ofertas.java
 *
 * Created on 21/02/2010, 09:17:27 AM
 */

package vista;

import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import controlador.control_ofertas;
import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import modelo.conexion_base_de_datos;
import modelo.imagenes;
import modelo.materias;
import modelo.registro_ofertas;

/**
 *
 * @author AN
 */
public class ofertas extends javax.swing.JFrame {

    /** Creates new form ofertas */
    public ofertas() {
        initComponents();
this.setDefaultCloseOperation(javax.swing.JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(null);

      control_ofertas co = new control_ofertas(this);
            carrera.addItemListener(co);
            semestre.addItemListener(co);
            atras.addActionListener(co);
            siguiente.addActionListener(co);
            guardar.addActionListener(co);
            visor.addActionListener(co);

            buscar.addActionListener(co);
            modificar.addActionListener(co);

            activar.addChangeListener(co);


            
            this.addWindowListener(co);
            this.addMouseListener(co);


    }

    public JComboBox getAsignaturas() {
        return asignaturas;
    }

    public void setAsignaturas(JComboBox asignaturas) {
        this.asignaturas = asignaturas;
    }

    public JComboBox getCarrera() {
        return carrera;
    }

    public void setCarrera(JComboBox carrera) {
        this.carrera = carrera;
    }

    public JComboBox getDesde() {
        return desde;
    }

    public void setDesde(JComboBox desde) {
        this.desde = desde;
    }

    public JComboBox getDias() {
        return dias;
    }

    public void setDias(JComboBox dias) {
        this.dias = dias;
    }

    public JTextField getDocente() {
        return docente;
    }

    public void setDocente(JTextField docente) {
        this.docente = docente;
    }

    public JLabel getSalones() {
        return salones;
    }

    public void setSalones(JLabel salones) {
        this.salones = salones;
    }

    public JComboBox getSemestre() {
        return semestre;
    }

    public void setSemestre(JComboBox semestre) {
        this.semestre = semestre;
    }

    public JComboBox getHasta() {
        return hasta;
    }

    public void setHasta(JComboBox hasta) {
        this.hasta = hasta;
    }

    public JTextField getCapacidad() {
        return capacidad;
    }

    public void setCapacidad(JTextField capacidad) {
        this.capacidad = capacidad;
    }

    public JCheckBox getActivar() {
        return activar;
    }

    public void setActivar(JCheckBox activar) {
        this.activar = activar;
    }

    public JButton getBuscar() {
        return buscar;
    }

    public void setBuscar(JButton buscar) {
        this.buscar = buscar;
    }

    public JButton getModificar() {
        return modificar;
    }

    public void setModificar(JButton modificar) {
        this.modificar = modificar;
    }

    public JTextField getPosicion() {
        return posicion;
    }

    public void setPosicion(JTextField posicion) {
        this.posicion = posicion;
    }

    public JButton getGuardar() {
        return guardar;
    }

    public void setGuardar(JButton guardar) {
        this.guardar = guardar;
    }

    public JLabel getPeriodo() {
        return periodo;
    }

    public void setPeriodo(JLabel periodo) {
        this.periodo = periodo;
    }

    public JComboBox getLista_docente() {
        return lista_docente;
    }

    public void setLista_docente(JComboBox lista_docente) {
        this.lista_docente = lista_docente;
    }


















    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        carrera = new javax.swing.JComboBox();
        semestre = new javax.swing.JComboBox();
        asignaturas = new javax.swing.JComboBox();
        desde = new javax.swing.JComboBox();
        hasta = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        docente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dias = new javax.swing.JComboBox();
        capacidad = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        posicion = new javax.swing.JTextField();
        activar = new javax.swing.JCheckBox();
        buscar = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        lista_docente = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        salones = new javax.swing.JLabel();
        periodo = new javax.swing.JLabel();
        visor = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        siguiente = new javax.swing.JButton();
        guardar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("MATERIAS OFERTADAS.......Desarrollado por Ing. Cusatti Andy");

        carrera.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        carrera.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "INGENIERIA MECANICA", "LIC. EDUCACION INTEGRAL", "LIC. CONTADURIA PUBLICA", "LIC. ECONOMIA SOCIAL", "TSU EN TURISMO", "INGENIERIA AERONAUTICA", "INGENIERIA CIVIL", "INGENIERIA ELECTRICA", "INGENIERIA ELECTRONICA", "INGENIERIA DE SISTEMAS", "INGENIERIA DE TELECOMUNICACIONES", "TSU EN ENFERMERIA", "LIC. EN ADMINISTRACION Y GESTION MUNICIPAL", "LIC. EN ENFERMERIA", "LIC. EN ADMINISTRACION DE DESASTRE", "TSU EN MECANICA DENTAL", "LIC. EN TURISMO", "TSU EN COMUNICACIONES Y ELECTRONICA", "TSU EN ANALISIS Y DISEÑO DE SISTEMAS" }));
        carrera.setToolTipText("Seleccione la carrera en donde desea ofertar la materia");
        carrera.setName("carrera"); // NOI18N

        semestre.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        semestre.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRIMERO", "SEGUNDO", "TERCERO", "CUARTO", "QUINTO", "SEXTO", "SEPTIMO", "OCTAVO", "NOVENO", "DECIMO" }));
        semestre.setToolTipText("Semestre de la carrera");
        semestre.setName("semestre"); // NOI18N

        asignaturas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        asignaturas.setToolTipText("Nombre de la materia");

        desde.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        desde.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "vacio" }));
        desde.setToolTipText("Hora de entrada de la materia");

        hasta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        hasta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "vacio" }));
        hasta.setToolTipText("Hora de salida de la materia");

        jLabel1.setText("DESDE");

        jLabel2.setText("HASTA");

        docente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        docente.setToolTipText("Nombre del docente a impartir la materia");

        jLabel3.setText("Docente: ");

        jLabel4.setText("DIAS");

        dias.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dias.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LUNES", "MARTES", "MIERCOLES", "JUEVES", "VIERNES", "SABADO", "DOMINGO" }));
        dias.setToolTipText("Dia en la que se vera la materia");

        capacidad.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        capacidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        capacidad.setText("35");
        capacidad.setToolTipText("Cantidad maxima de alumnos que se pueden inscribir en esta seccion de acuerdo a la materia");

        jLabel5.setText("CAPACIDAD");

        posicion.setToolTipText("Se coloca la posicion de la materia que se desea buscar. (Parametro que da el VISOR)");
        posicion.setEnabled(false);

        activar.setText("Posicion");
        activar.setToolTipText("Activa y desactiva las opciones de BUSCAR y MODIFICAR");

        buscar.setText("BUSCAR");
        buscar.setToolTipText("Busca la materia asociada a la posicion donde se encuentra con todos sus parametros");
        buscar.setEnabled(false);

        modificar.setText("MODIFICAR");
        modificar.setToolTipText("Modifica todos los valores de la  materia asociado a la posicion y luego se desactivan los controles");
        modificar.setEnabled(false);

        lista_docente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "ABRAHAM SALAZAR, JORGE LUIS", "ALARZE LÓPEZ, ALIRIO ANTONIO", "ALVAREZ GUEVARA, ARACELYS YADIRA", "ALVAREZ LEÓN, JULHAY JOSEFINA", "ALVAREZ RUIZ, AREANNY GRACIELA", "ANFUSO LUIZZO, CONCETTA ROSALINDA", "APONTE AZUAJE, JOSÉ ROMAN", "APONTE BERNAL, YELITZA MAYORLI", "ARIAS FLORES, CIXTO BERNARDO", "ARIAS OLIVEROS, BETSABETH ROSY", "ARTEAGA ROMERO, ALEXANDER EDUARDO", "AVENDAÑO DE BERMUDEZ, NORKA VIRGINIA", "BAPTISTA LEÓN, THAIS COROMOTO", "BARCO LOYO, LUIS ANTONIO", "BECERRA VIELMA, JAVIER EMILIO", "BELLO DÍAZ, JUAN JOSÉ", "BELLO MEDINA, FELIX ANTONIO", "BENCOMO DE HERNÁNDEZ, ORFAS NICOLASA", "BLANCO BOYER, JOSÉ MANUEL", "BLANCO DE SOJO, CARMEN FELICIA", "BOLÍVAR QUINTANA, TEODULO JOSÉ", "BRACHO VILLEGAS, JOSÉ LUIS", "BRICEÑO DE RIVAS, MIRIAM DEL CARMEN", "BRITO ESPINOZA, MILAGRO DEL VALLE", "BUSTILLO SALAZAR, CARMEN MARITZA", "CABRERA BARRIOS, RAFAEL EDUARDO", "CABRERA BRITO, FLOR DEL VALLE", "CABRERA SOLANO, DHORYVEL MILAGROS", "CÁCERES MEDINA, LUIS ALFREDO", "CADENAS, ADELA MORAIRA", "CANNATA GONZÁLEZ, CARMEN INDIRA", "CANO CORTÉS, RICARDO", "CÁRDENAS RANGEL, LINDAYS CAROLINA", "CARDOZO ROA, CARMEN IDALIA", "CARDOZO TINOCO, CARMEN ROSA", "CARRASCO, MARIANA", "CARRASQUEL TORO, ÁNGEL HUMBERTO", "CARRILLO, MARÍA ESPERANZA", "CARRILLO LUJÁN, ABDEL", "CARVAJAL SALAZAR, ANA ZULIN", "CASTELLANO ORTEGA, ALEXANDER JOSÉ", "CASTILLO APONTE, RAFAEL JOSÉ", "CASTILLO DE MILANO, JANNETTE JOSEFINA", "CASTILLO SALAZAR, ORLANDO ENRIQUE", "CEBALLOS PÉREZ, EYRA TERESA", "CEPEDA CIFUENTES, ÁLVARO JUNIOR", "CHAPARRO GÓMEZ, YELITZI VANESSA", "CHAVEZ MARTÍNEZ, MIRIAN REGINA", "CISNEROS SOSA, LAURA MARIELA", "COBOS QUINTANA, YSLAIDA SOLANGE", "COLMENARES ALFONZO, PABLO RAFAEL", "COLMENARES ALVAREZ, HECTOR EDUARDO", "CONSTANTINI, DEBORA", "CONTRERAS NATERA, ÁNGEL ANTONIO", "CORREA MIRANDA, OSCAR ENRIQUE", "CORREA PÉREZ, LUCIO ANTONIO", "CROQUER MILANO, LUCIDIA CARIDAD", "CUSATTI MACUARE, ANDY ALDELMARO", "DE JESÚS LEÓN, MIREYA", "DEBIA HERNANDEZ, FRAY HERNAN", "DELGADO, CRUZ EDGAR", "DELGADO MENDOZA, DARKYS JANETH", "DELGADO PÉREZ, ALBER EDUARDO", "DEPABLOS ACEITUNO, YANIXA JOSEFINA", "DÍAZ MONTES, ZAIDA", "DUARTE BRICEÑO, MORELBA ELENA", "DUARTE PÉREZ, ROSA ANDREINA", "DUARTE PÉREZ, JESÚS CLARET", "DURÁN JIMENEZ, JOSÉ IRENE", "DURÁN MANZO, GLADYS ALINDA", "ECHARRY GUTIÉRREZ, ASLEY BACH", "ECHENIQUE BOLÍVAR, BELKYS SOLANGE", "ESCALANTE HERRERA, LOURDES YAYRI", "ESCOBAR ESCOBAR, NANCY CLARET", "ESCOBAR RUIZ, DOUGLAS VIRGILIO", "FERREIRA, ANA TERESA", "FIGUEROA OSORIO, JUAN DIEGO", "FLORES MANRIQUE, MIRIAM COROMOTO", "FLORES NIEVES, RAFAEL", "FUMERO DOMINGUEZ, ELIMAR TERESA", "GALARZA TORRES, JAIDANA CATHERY", "GALINDEZ GARCÍA, MIGDALIA COROMOTO", "GAMBOA ARCHILA, WILLIAM FRANCISCO", "GARCÍA BALLESTER, NEREIDA JOSEFINA", "GARCÍA CAMPOS, AURY DE LOS ÁNGELES", "GARCÍA FERMÍN, YUDITH COROMOTO", "GARCÍA HERNÁNDEZ, SERGIO RAFAEL", "GARCÍA JAIME, LUIS", "GARCÍA MAGO, CLEMYS DEL VALLE", "GÓMEZ CAMACHO, ALBA LUCIA", "GÓMEZ VIVAS, PATRICIA ALEJANDRA", "GONZÁLEZ, VILMA", "GONZÁLEZ GAMEZ, JUAN CARLOS", "GONZÁLEZ GONZÁLEZ, MARÍA DOLORES", "GONZÁLEZ RUIZ, XAVIER ALEJANDRO", "GOTTOS PELAEZ, JESÚS EDUARDO", "GUAITA SANTODOMINGO, CÉSAR AUGUSTO", "GUERRERO CASTILLO, JOSÉ GEOVANNY", "GUILLÉN MUJICA, ALEJANDRO", "HALAWI DARWICHE, JULUD YELITZA", "HALEGÜEY PORRA, LIBAN DEL CARMEN", "HERNANDEZ BENCOMO, LEYDI", "HERRAT DE SILVA, MAIQUEL YNOCENCIA", "HERRERA APODACA, GRISEL VICTORIA", "HERRERA CAMPOS, EVELIN MARÍA", "HERRERA ECHEZURÍA, INÉS MARÍA", "HERRERA HERAS, JUAN MANUEL", "HERRERA SILVA, PILAR EUGENIA", "HIDALGO ALVARADO, JOSÉ AUGUSTO", "KANDALAFT ORDOÑEZ, ALEJANDRO JOSÉ", "KHALIL BAKHOS, MARÍA", "LECUNA ROMERO, DIRAHISA MERCEDES", "LEÓN ROJAS, FRANCYNAT", "LINARES DE BARBOLINE, ISABEL TERESA", "LÓPEZ, GLADYS MARÍA", "LÓPEZ GARCÍA, YILENA ANDREINA", "LÓPEZ GÓMEZ, FRIORDALIZA", "LÓPEZ GUAIRA, LAURA LIRALY", "LÓPEZ INDRIAGO, JUAN JOSÉ", "LÓPEZ MUDARRA, REINALDO JOSÉ", "LOVERA BLANCO, JERMAIN JOSÉ", "LUCIANI RINCÓN, TEOTISTE MARÍA", "LUCIANI RINCÓN, YAMILETH ANGÉLICA", "LUGO GÓMEZ, LUISA JOSEFINA", "LUIS GONZÁLEZ, CAROLINA", "MACHADO ARRECHEDERA, JAVIER JOSÉ", "MACHADO PADRÓN, GLORIA ISABEL", "MANAURE SÁNCHEZ, YULIBETH DUBRASCA", "MARÍN DE NICOLO, WENDOLYNE", "MARTÍNEZ ACOSTA, FELGRY JACKNIRY", "MARTÍNEZ LASCARRO, JAIRO ENRIQUE", "MARTÍNEZ MONTERO, RICHARD ALEXANDER", "MARTÍNEZ ROJAS, JOSÉ CARLOS", "MARVAL MANAURE, GERSON JOEL", "MASTRANGELO LÓPEZ, SIMÓN EDUAR", "MATHISON SALAZAR, ODRA KARYM", "MAYORCA FERNÁNDEZ, RUBLIO JESÚS", "MEDINA, ANA JOSEFINA", "MELCHOR BELTRAN, EDIOURKYS DEL VALLE", "MENDIBLE SÁNCHEZ, ARNALDO COROMOTO", "MERCHÁN REYES, DARWIZ JOSÉ", "MEZA DE BAGLIO, ANA GRACIELA", "MEZA DE SUÁREZ, BLANCA DIOMIRA", "MIJARES ROSAS, GRISEL DEL CARMEN", "MINSERO AMARO, LILIANA DE LOURDES", "MOLINA DE GUILLEN, MIRELYS JOSEFINA", "MÓNACO D´ANGELO, PANFILINO", "MONROY DE GONZÁLEZ, IRENE RAMONA", "MONTAQUILA DE CHIRINOS, ANGELA ALIDA", "MORALES MARTÍNEZ, GIORGINA", "MORALES ORDOÑEZ, LAURA MARÍA", "MORALES ORDOÑEZ, ANA REBECA", "MORENO DE COLLAZO, ERCILIA TRINIDAD", "MORENO REBOLLEDO, INDIRA ROSA", "MORGADO CASAÑAS, JUANA MIGUELINA", "MORILLO, FREDDY IVÁN", "MUJICA OJEDA, GLADYS AMARILYS", "MUÑOZ, RICHARD JOSÉ", "NARANJO MORILLO, JAIME JOSÉ", "NAVARRO REINA, ROCIO FRANCISCA", "NIEVES, AUDREY DE JESÚS", "NIEVES DE FREITES, JENNIFER KARINA", "NUÑEZ TENORIO, GREGORIA JOSEFINA", "OCANDO CONTRERAS, CARLOS LUIS", "OCANDO FRANCO, ANA MARÍA", "OROPEZA PLAZA, MANUEL FELIPE", "OSORIO CARRASQUEL, EDGAR ANTONIO", "OSORIO CARRASQUEL, MARJORIE ANTONIETTA", "OSORIO RAMÍREZ, MARÍA ALEXANDRA", "OVALLES ALVARADO, CARLOS ARGENIS", "PADRÓN SÁNCHEZ, VÍCTOR JOSÉ", "PAEZ DE RODRÍGUEZ, MYRIAM", "PAEZ PENA, ODALYS COROMOTO", "PALACIOS MARTÓNEZ, NILSON", "PALUMBO SUNIAGA, CAROLINA", "PAPPATERRA MENDOZA, YSBEL NOEMÍ", "PARRA ALVARADO, LEA CAROLINA", "PARRA RODRÍGUEZ, JUAN JOSÉ", "PARRAGA GARCÍA, HUGO", "PATIÑO REQUENA, AURYS EGLEE", "PEDRÁ RODRÍGUEZ, JESÚS ALEJANDRO", "PEÑA ROJAS, MARÍA ALVINA", "PEÑA ROJAS, JORGE ALEZANDER", "PEÑA VILORIA, RICHAR ALEXIS", "PERALTA GARCÍA, MARYURI ZAYDEÉ", "PÉREZ DA SILVA, ELVIC RAFAEL", "PÉREZ DE AGUIRRE, SUSANA COROMOTO", "PÉREZ GONZALEZ, YSAURA JOSEFINA", "PÉREZ JUSTO, YARITZA DEL CARMEN", "PÉREZ RODRÍGUEZ, ADRIANA LISETTE", "PINTO DE CATAMO, YONMILEY JOSEFINA", "PINTO PARRA, EYSRAEL", "PLATA BRIÑEZ, LUIS EDUARDO", "PRADET CALDERA, RODNEY JOSÉ", "RAMÍREZ BRACHO, MAURY YHADIRA", "RAMÍREZ CAÑIZALES, MADELEYN", "RAMOS ESCALONA, CARLOS ALBERTO", "REINA ORTUÑO, ENNODIO JOSÉ", "RENWICK VARGAS, RAFAEL JOSÉ", "RETAMOZO MOTTA, JORGE ANTONIO", "REY, LUZ HERMINIA", "REYES KINSLER, CARLOS MANUEL", "REYES MACHUCA, MÓNICA ALEXANDRA", "REYES SANTAELLA, FRANCISCO JAVIER", "RIVA DÍAZ, MORIELBA", "RIVAROLI BELTRÁN, EVELING MARÍA", "RIVAS MEDINA, CARLOS JOSÉ", "RIVAS TALAVERA, LORELY DEL VALLE", "ROBLES CEPEDA, MIGUEL ÁNGEL", "RODRÍGUEZ AGUILERA, JOYCE GREGORIO", "RODRÍGUEZ BOGADO, JOSEANY JACQUELINE", "RODRÍGUEZ COLMENARES, NICOLAS ALFONSO", "RODRÍGUEZ DE BOLÍVAR, KARINA COROMOTO", "RODRÍGUEZ DÍAZ, WALCELIO ANTONIO", "RODRÍGUEZ GONCALVEZ, WALTER BERNARDO", "RODRÍGUEZ HERRERA, HUMBERTO", "RODRÍGUEZ PÉREZ, MARÍA DE LOURDES", "RODRÍGUEZ VALERA, ALICIA EDUVIGIS", "ROJAS MUÑOZ, OMAIRA JOSEFINA", "ROJAS TORRENS, LIZMAR DEL VALLE", "ROJAS ZABRANO, SUGHEIS CAROLINA", "ROMERO DE ECHARRI, MARIA ANGELICA", "RUIZ HERRERA, SARAY AURORA", "RUIZ VALLADARES, FRANCISCO JOSE", "SÁCHEZ AÑEZ, LUIS ALFONZO", "SALAZAR BARRAEZ, BERTHELENA", "SALAZAR PALMA, EDGAR JOSÉ", "SALAZAR PÉREZ, ARLEN DEL CARMEN", "SALINAS FERNÁNDEZ, MARLENE GUADALUPE", "SÁNCHEZ, EDGAR", "SANCHEZ ARVELÁEZ, HILDA ROSA", "SÁNCHEZ CASTILLO, OMAIRA YULIMA", "SÁNCHEZ MORALES, LUSBEL MARGARITA", "SCOTT DE PERAZA, SILVIA YAMILET", "SCOTT DE RAMOS, TERESA MARIBEL", "SCUOPPO SANDOMENICO, ELENA MARÍA", "SEGOVIA MAYORCA, JOSE DE LA TRINIDAD", "SEIJAS BONNIER, HILARION RAMÓN", "SISO, ALEN JOSÉ", "SOLORZANO DE GONCALVEZ, ROSA MARISEL", "SORIANO ANDREA, RAFAEL ELEAZAR", "SUÁREZ BARCARCEL, EFREN JAVIER", "TAGLIAFERRO DE PEÑA, MARIELA JOSEFINA", "TELISSE JAHUBIAN, BRIGITTE", "TELLEZ COLMENARES, SONIA CRISTINA", "TORO FIGUEREDO, YELITZA ESTHER", "TORO MORA, ANARELYS", "TROVAT ASCANIO, VALENTINA ANTONELY", "URRACA PIÑERO, LUCIO JÓSE", "URUETA TORO, NANCY ESTHER", "VALBUENA GUERRERO, VICENTE DE JESÚS", "VALDEZ HEREDIA, MIGUEL ÁNGEL", "VÁSQUEZ BELISARIO, YRAMA JOSEFINA", "VÁSQUEZ UVIEDO, ADALY ISAHAMS", "VEGA CARRUYO, BLANCA NATHALY", "VEGAS PACHECO, LUIS ERNESTO", "VELÁSQUEZ HUNG, KARIM SOFÍA", "VELÁSQUEZ LORENZO, LUIS ALEXANDER", "VENTHENCOURT MORILLO, JUDITH COROMOTO", "VERGARA PERNIA, NELSÓN JOSÉ", "VIELMA LINARES, DENIS JACKELIN", "VILLALOBOS PAZ, FATIMA COROMOTO", "VILLAMIZAR NIEVES, CLARIZA MARGOTH", "VIVAS RUÍZ, DIXÓN JOEL", "YANEZ, ADRIANA", "ZAMBRANO ARAQUE, OSWALDO RAFAEL", "ZAMBRANO BARRERA, ZULAY MERCEDES", "ZAMBRANO CARRILLO, ANGÉLICA MARÍA", "ZAMBRANO DE ÁLVAREZ, NUBIA MARÍA", "ZARA ARIAS, ANA JOSEFINA" }));

        salones.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        salones.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        salones.setText("IM-101");

        periodo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        periodo.setText("2-2011");

        visor.setText("VISOR");
        visor.setToolTipText("Herramienta para visualizar las materias ofertadas");

        atras.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        atras.setText("atras");
        atras.setToolTipText("Retrocede en secciones");
        atras.setName("atras"); // NOI18N

        siguiente.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        siguiente.setText("siguiente");
        siguiente.setToolTipText("Avanza en secciones");

        guardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        guardar.setText("GUARDAR");
        guardar.setToolTipText("Guarda todos los parametros de la materia a ofertar");

        jLabel6.setText("SECCION");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(atras, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(siguiente))
                            .addComponent(salones, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(periodo)
                                .addGap(44, 44, 44))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(periodo)
                .addGap(31, 31, 31)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salones, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(siguiente)
                    .addComponent(atras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(visor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(carrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lista_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(docente, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(asignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 28, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(activar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(modificar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semestre, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carrera, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(asignaturas, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(desde, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hasta, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(dias, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lista_docente, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(docente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(activar)
                    .addComponent(posicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscar)
                    .addComponent(modificar))
                .addContainerGap(67, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {

         NimRODTheme nt = new NimRODTheme();

        nt.setPrimary( new Color(153,244,51));
        nt.setPrimary1( new Color(133,224,31));
        nt.setPrimary2( new Color(143,234,41));
        nt.setPrimary3( new Color(153,244,51));

        nt.setSecondary(new Color(222,230,250));
        nt.setSecondary1(new Color(202,210,230));
        nt.setSecondary2(new Color(212,220,240));
        nt.setSecondary3(new Color(222,230,250));

        nt.setMenuOpacity(20);
        nt.setFrameOpacity(20);
        nt.setOpacity(20);

            NimRODLookAndFeel NimRODLF = new NimRODLookAndFeel();
            NimRODLF.setCurrentTheme( nt);
            UIManager.setLookAndFeel( NimRODLF);


        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ofertas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox activar;
    private javax.swing.JComboBox asignaturas;
    private javax.swing.JButton atras;
    private javax.swing.JButton buscar;
    private javax.swing.JTextField capacidad;
    private javax.swing.JComboBox carrera;
    private javax.swing.JComboBox desde;
    private javax.swing.JComboBox dias;
    private javax.swing.JTextField docente;
    private javax.swing.JButton guardar;
    private javax.swing.JComboBox hasta;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox lista_docente;
    private javax.swing.JButton modificar;
    private javax.swing.JLabel periodo;
    private javax.swing.JTextField posicion;
    private javax.swing.JLabel salones;
    private javax.swing.JComboBox semestre;
    private javax.swing.JButton siguiente;
    private javax.swing.JButton visor;
    // End of variables declaration//GEN-END:variables

}
