/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * procesos.java
 *
 * Created on 26/09/2011, 02:34:28 PM
 */

package vista;

import controlador.control_proceso;
import javax.swing.JTextArea;

/**
 *
 * @author AN
 */
public class procesos extends javax.swing.JFrame {

    /** Creates new form procesos */
    public procesos() {
        initComponents();
        
        control_proceso cp = new control_proceso(this);
        procesar.addActionListener(cp);
        analizar.addActionListener(cp);




    }

    
    
    
    
    public JTextArea getResumen() {
        return resumen;
    }

    public void setResumen(JTextArea resumen) {
        this.resumen = resumen;
    }


    





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        procesar = new javax.swing.JButton();
        analizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        resumen.setColumns(20);
        resumen.setRows(5);
        jScrollPane1.setViewportView(resumen);

        jLabel1.setText("RESUMEN:");

        procesar.setText("PROCESAR ACTAS");

        analizar.setText("ANALIZAR");
        analizar.setToolTipText("Se analiza los calculos de las actas, estudiantes procesados, aprobados y reprobados, errores y los que van a reparar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 366, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(146, 146, 146)
                        .addComponent(procesar, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(analizar))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(procesar)
                    .addComponent(jLabel1)
                    .addComponent(analizar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 502, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new procesos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton analizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton procesar;
    private javax.swing.JTextArea resumen;
    // End of variables declaration//GEN-END:variables

}
