/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * progreso.java
 *
 * Created on 23/11/2010, 10:55:40 AM
 */

package vista;

import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author AN
 */
public class progreso extends javax.swing.JFrame {

    /** Creates new form progreso */
    public progreso() {
        initComponents();
        this.setLocationRelativeTo(null);



    }

    public JLabel getInformacion_1() {
        return informacion_1;
    }

    public void setInformacion_1(JLabel informacion_1) {
        this.informacion_1 = informacion_1;
    }

  

    public JProgressBar getPrincipal() {
        return principal;
    }

    public void setPrincipal(JProgressBar principal) {
        this.principal = principal;
    }

  





    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        principal = new javax.swing.JProgressBar();
        informacion_1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("PROGRESO...!");

        principal.setMaximum(1000);
        principal.setStringPainted(true);

        informacion_1.setText("informacion_1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(principal, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
                    .addComponent(informacion_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(principal, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(informacion_1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        try {
            NimRODTheme nt = new NimRODTheme();
            nt.setPrimary(new Color(153, 244, 51));
            nt.setPrimary1(new Color(133, 224, 31));
            nt.setPrimary2(new Color(143, 234, 41));
            nt.setPrimary3(new Color(153, 244, 51));
            nt.setSecondary(new Color(222, 230, 250));
            nt.setSecondary1(new Color(202, 210, 230));
            nt.setSecondary2(new Color(212, 220, 240));
            nt.setSecondary3(new Color(222, 230, 250));
            nt.setMenuOpacity(20);
            nt.setFrameOpacity(20);
            nt.setOpacity(20);
            NimRODLookAndFeel NimRODLF = new NimRODLookAndFeel();
            NimRODLF.setCurrentTheme(nt);
            UIManager.setLookAndFeel(NimRODLF);

            java.awt.EventQueue.invokeLater(new Runnable() {

                public void run() {
                    new progreso().setVisible(true);
                }
            });
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(progreso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel informacion_1;
    private javax.swing.JProgressBar principal;
    // End of variables declaration//GEN-END:variables

}
