/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * reporte.java
 *
 * Created on 12/03/2010, 08:28:43 AM
 */

package vista;

import java.util.LinkedList;
import javax.swing.JTextArea;

/**
 *
 * @author AN
 */
public class reporte extends javax.swing.JFrame {

    private LinkedList<String> reportando= new LinkedList<>();



    /** Creates new form reporte */
    public reporte() {
        initComponents();

        
for(int i=0; i<this.getReportando().size(); i++){


}




    }

    public JTextArea getNoticia() {
        return noticia;
    }

    public void setNoticia(JTextArea noticia) {
        this.noticia = noticia;
    }

    public LinkedList<String> getReportando() {
        return reportando;
    }

    public void setReportando(LinkedList<String> reportando) {
        this.reportando = reportando;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        noticia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORTE");

        noticia.setColumns(20);
        noticia.setRows(5);
        jScrollPane1.setViewportView(noticia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea noticia;
    // End of variables declaration//GEN-END:variables

}
