/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * suspenciones.java
 *
 * Created on 21/09/2011, 12:23:21 PM
 */

package vista;

import controlador.control_suspensiones;
import javax.swing.*;

/**
 *
 * @author AN
 */
public class suspenciones extends javax.swing.JFrame {

    /** Creates new form suspenciones */
    public suspenciones() {
        initComponents();
        setLocationRelativeTo(null);
        
        control_suspensiones cs = new control_suspensiones(this);
        buscar.addActionListener(cs);
        cambiar.addActionListener(cs);
        analizar.addActionListener(cs);
        masivo.addActionListener(cs);


    }





    public JComboBox getActivo() {
        return activo;
    }

    public void setActivo(JComboBox activo) {
        this.activo = activo;
    }

    public JButton getBuscar() {
        return buscar;
    }

    public void setBuscar(JButton buscar) {
        this.buscar = buscar;
    }

    public JButton getCambiar() {
        return cambiar;
    }

    public void setCambiar(JButton cambiar) {
        this.cambiar = cambiar;
    }

    public JTextField getCedula() {
        return cedula;
    }

    public void setCedula(JTextField cedula) {
        this.cedula = cedula;
    }

    public JCheckBox getBloqueo() {
        return bloqueo;
    }

    public void setBloqueo(JCheckBox bloqueo) {
        this.bloqueo = bloqueo;
    }

    public JTextArea getResumen() {
        return resumen;
    }

    public void setResumen(JTextArea resumen) {
        this.resumen = resumen;
    }

    public JButton getAnalizar() {
        return analizar;
    }

    public void setAnalizar(JButton analizar) {
        this.analizar = analizar;
    }





    












    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cedula = new javax.swing.JTextField();
        activo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        cambiar = new javax.swing.JButton();
        bloqueo = new javax.swing.JCheckBox();
        analizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resumen = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        masivo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SUSPENCIONES");

        cedula.setToolTipText("Ingrese la cedula del estudiante");

        activo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        activo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SI", "NO" }));
        activo.setEnabled(false);

        jLabel1.setText("CEDULA:");

        jLabel2.setText("ACTIVO? :");

        buscar.setText("BUSCAR");
        buscar.setToolTipText("Busca la condicion actual en la que se encuentra el estudiante");

        cambiar.setText("CAMBIAR");
        cambiar.setToolTipText("Esto permite hacer efectivo el camio de activo o inactivo del estudiante");
        cambiar.setEnabled(false);

        bloqueo.setText("BLOQUEO INSCRIPCION");

        analizar.setText("ANALIZAR");
        analizar.setEnabled(false);

        resumen.setColumns(20);
        resumen.setLineWrap(true);
        resumen.setRows(5);
        resumen.setWrapStyleWord(true);
        jScrollPane1.setViewportView(resumen);

        jLabel3.setText("RESUMEN");

        masivo.setText("MASIVO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(activo, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(buscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(analizar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(bloqueo)
                        .addGap(18, 18, 18)
                        .addComponent(cambiar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(masivo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 220, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(228, 228, 228))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(activo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(analizar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(93, 93, 93))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addGap(101, 101, 101)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cambiar)
                            .addComponent(bloqueo))
                        .addGap(18, 18, 18)
                        .addComponent(masivo)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new suspenciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox activo;
    private javax.swing.JButton analizar;
    private javax.swing.JCheckBox bloqueo;
    private javax.swing.JButton buscar;
    private javax.swing.JButton cambiar;
    private javax.swing.JTextField cedula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton masivo;
    private javax.swing.JTextArea resumen;
    // End of variables declaration//GEN-END:variables

}
