/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * guardando.java
 *
 * Created on 17/04/2011, 02:49:06 PM
 */

package modelo;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author AN
 */
public class guardando extends javax.swing.JPanel {

    /** Creates new form guardando */
    public guardando() {
        initComponents();
        
    }

    public JFileChooser getSeleccion() {
        return seleccion;
    }

    public void setSeleccion(JFileChooser seleccion) {
        this.seleccion = seleccion;
    }

   



    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccion = new javax.swing.JFileChooser();

        setName("contenedor"); // NOI18N

        seleccion.setBackground(new java.awt.Color(204, 255, 204));
        seleccion.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        seleccion.setFileSelectionMode(javax.swing.JFileChooser.FILES_AND_DIRECTORIES);
        seleccion.setFont(new java.awt.Font("Lucida Handwriting", 0, 18)); // NOI18N
        seleccion.setName("seleccion"); // NOI18N
        seleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(seleccion, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void seleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionActionPerformed
     

        System.out.println("evento guardando "+evt.getActionCommand()+" padre "+this.getParent().getName()+" listeners : ");
       

        
    }//GEN-LAST:event_seleccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser seleccion;
    // End of variables declaration//GEN-END:variables

}
